#!/bin/bash

#g++ -Wall -W -Werror *.cpp -o output -lGLU -lGL -lX11 || exit 1

g++ -Wall -g -W -Werror -I ./src/include src/*.cpp src/**/*.cpp src/**/**/*.cpp -o bin/output -lGLU -lGL -lGLEW -lX11 || exit 1
