#!/bin/bash

g++ -Wall -g -W -Werror -Wno-unused-parameter -Wno-unused-variable \
    -I ./src/include \
    src/*.cpp \
    src/**/*.cpp \
    src/**/**/*.cpp \
    -o bin/output \
    -lGLU -lGL -lGLEW -lX11 || exit 1
